import type { Metadata } from "next";
import "./globals.css";

import { Providers } from "./providers";
import { QueryClientProvider } from "@tanstack/react-query";
import { queryClient } from "@/services/queryClient";
import { AuthProvider } from "@/context/authContext";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Blog Edson",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className="min-h-screen bg-gray-50 text-gray-900">
        <QueryClientProvider client={queryClient}>
          <AuthProvider>
            <Providers>
              {children}
              <Toaster
                position="top-right"
                toastOptions={{
                  style: {
                    borderRadius: "12px",
                    background: "#111",
                    color: "#fff",
                  },
                }}
              />
            </Providers>
          </AuthProvider>
        </QueryClientProvider>
      </body>
    </html>
  );
}
